'use client';

import { useState } from 'react';
import ATSReport from '@/components/rolepitch/ATSReport';

const CSS = `
  :root {
    --bg: oklch(0.98 0.006 248);
    --surface: oklch(0.955 0.009 248);
    --border: oklch(0.86 0.015 248);
    --border-subtle: oklch(0.91 0.01 248);
    --accent: oklch(0.50 0.19 248);
    --accent-dim: oklch(0.50 0.19 248 / 0.10);
    --green: oklch(0.55 0.17 155);
    --green-dim: oklch(0.55 0.17 155 / 0.10);
    --red: oklch(0.58 0.19 25);
    --red-dim: oklch(0.58 0.19 25 / 0.10);
    --amber: oklch(0.60 0.16 80);
    --amber-dim: oklch(0.60 0.16 80 / 0.10);
    --text: oklch(0.16 0.03 248);
    --text-muted: oklch(0.44 0.04 248);
    --text-faint: oklch(0.62 0.03 248);
    --mono: 'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, monospace;
    --sans: 'DM Sans', sans-serif;
  }
  .rc-root { font-family: var(--sans); background: var(--bg); color: var(--text); min-height: 100vh; -webkit-font-smoothing: antialiased; padding: 24px 16px; }
  .rc-nav { max-width: 1080px; margin: 0 auto 28px; display: flex; align-items: center; justify-content: space-between; gap: 14px; }
  .rc-brand { display: flex; align-items: center; gap: 8px; text-decoration: none; color: var(--text); }
  .rc-logo { width: 26px; height: 26px; background: var(--accent); border-radius: 6px; display: flex; align-items: center; justify-content: center; }
  .rc-btn { border-radius: 10px; padding: 9px 14px; font-size: 13px; font-weight: 700; cursor: pointer; font-family: var(--sans); }
  .rc-btn-primary { background: var(--accent); color: white; border: none; }
  .rc-btn-outline { background: transparent; color: var(--accent); border: 1px solid var(--accent); }
  @media print {
    .no-print, .ats-mobile-sticky, .ats-rail { display: none !important; }
    .rc-root { padding: 0 !important; }
  }
`;

export default function ReportClient({ row }) {
  const [copied, setCopied] = useState(false);
  const shareUrl = typeof window !== 'undefined' ? window.location.href : '';
  const startPath = () => {
    if (typeof window === 'undefined') return '/rolepitch/start';
    const host = window.location.hostname;
    return host === 'rolepitch.com' || host === 'www.rolepitch.com' ? '/start' : '/rolepitch/start';
  };

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      window.prompt('Copy this report link', shareUrl);
    }
  };

  return (
    <>
      <style>{CSS}</style>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@500;600;700&display=swap" rel="stylesheet" />
      <div className="rc-root">
        <div className="rc-nav no-print">
          <a href="/" className="rc-brand">
            <div className="rc-logo">
              <svg width="13" height="13" viewBox="0 0 14 14" fill="none"><path d="M2 3h10M2 7h7M2 11h9" stroke="white" strokeWidth="1.5" strokeLinecap="round" /></svg>
            </div>
            <span style={{ fontWeight: 800, fontSize: 15, letterSpacing: '-0.02em' }}>RolePitch</span>
          </a>
          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={() => window.print()} className="rc-btn rc-btn-outline">Save as PDF</button>
            <button onClick={copy} className="rc-btn rc-btn-primary">{copied ? 'Copied!' : 'Share link'}</button>
          </div>
        </div>

        <ATSReport
          critique={row.critique_json}
          critiqueId={row.id}
          targetContext={row.target_context}
          createdAt={row.created_at}
          expiresAt={row.expires_at}
          shareUrl={shareUrl}
          onShare={copy}
          isShared
          onTailor={() => { window.location.href = startPath(); }}
        />

        <div style={{ maxWidth: 1080, margin: '24px auto 0', paddingTop: 16, borderTop: '1px solid var(--border-subtle)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}>
          <span style={{ fontSize: 11, color: 'var(--text-faint)' }}>Generated by RolePitch · rolepitch.com</span>
          <span style={{ fontSize: 11, color: 'var(--text-faint)' }}>Expires {new Date(row.expires_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span>
        </div>
      </div>
    </>
  );
}
